export const dynamic = 'force-dynamic';
export const maxDuration = 60;

import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth-options';
import { prisma } from '@/lib/prisma';
import { htmlToPdf } from '@/lib/pdf';
import { appBaseUrl } from '@/lib/app-url';
import { getPdfBrand } from '@/lib/company-brand';
import { getSessionLocale } from '@/lib/i18n/server';

function esc(str: string): string {
  return (str ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const fmtMoney = (v: number | null | undefined): string =>
  v ? '$' + v.toLocaleString('en-US', { maximumFractionDigits: 0 }) : '';

const fmtMoneyFull = (v: number | null | undefined): string =>
  '$' + (v ?? 0).toLocaleString('en-US', { maximumFractionDigits: 0 });

const fmtDate = (d: Date | string | null | undefined, locale: string): string => {
  if (!d) return '';
  const dt = typeof d === 'string' ? new Date(d) : d;
  if (isNaN(dt.getTime())) return '';
  return dt.toLocaleDateString(locale === 'es' ? 'es-ES' : 'en-US', { month: 'short', day: 'numeric', year: '2-digit' });
};

const LABELS = {
  en: {
    title: 'BUYOUT / CONTRACT TRACKING',
    trade: 'Trade', division: 'Div', type: 'Type', status: 'Status',
    proposal: 'Proposal', contracted: 'Contracted', cors: 'CORs', total: 'Total Value',
    targetContract: 'Target Contract', subOnSite: 'Sub On-Site', subcontractor: 'Subcontractor',
    summary: 'SUMMARY', contractBudget: 'Contract Budget', invested: 'Cash Invested',
    remaining: 'Remaining', generated: 'Generated by koduPM',
  },
  es: {
    title: 'COMPRAS / CONTROL DE CONTRATOS',
    trade: 'Oficio', division: 'Div', type: 'Tipo', status: 'Estado',
    proposal: 'Propuesta', contracted: 'Contratado', cors: 'CORs', total: 'Valor Total',
    targetContract: 'Contrato Meta', subOnSite: 'Sub en Obra', subcontractor: 'Subcontratista',
    summary: 'RESUMEN', contractBudget: 'Presupuesto Contrato', invested: 'Efectivo Invertido',
    remaining: 'Restante', generated: 'Generado por koduPM',
  },
} as const;

export async function GET(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const companyId = (session.user as any)?.companyId ?? '';

    const { searchParams } = new URL(request.url);
    const projectId = searchParams.get('projectId');
    if (!projectId) return NextResponse.json({ error: 'projectId is required' }, { status: 400 });

    const project = await prisma.project.findFirst({ where: { id: projectId, companyId } });
    if (!project) return NextResponse.json({ error: 'Project not found' }, { status: 404 });

    const items = await prisma.buyoutItem.findMany({
      where: { projectId },
      orderBy: { sortOrder: 'asc' },
    });

    const locale = await getSessionLocale();
    const L = LABELS[locale === 'es' ? 'es' : 'en'];
    const brand = await getPdfBrand(companyId, appBaseUrl(), 30);

    const trades = items.filter((i: any) => i.lineType !== 'Division');
    const totals = trades.reduce((acc: any, i: any) => ({
      proposal: acc.proposal + (i.proposalAmount || 0),
      contracted: acc.contracted + (i.contractedValue || 0),
      cors: acc.cors + (i.changeOrders || 0) + (i.pendingCor || 0),
      total: acc.total + (i.totalValueBudget || 0),
      invested: acc.invested + (i.cashFlowInvested || 0),
    }), { proposal: 0, contracted: 0, cors: 0, total: 0, invested: 0 });

    const rows = items.map((i: any) => {
      const isDiv = i.lineType === 'Division';
      if (isDiv) {
        return `<tr class="div"><td colspan="11">${esc(i.trade)}${i.divisionCode ? ` · ${esc(i.divisionCode)}` : ''}</td></tr>`;
      }
      return `<tr>
        <td class="desc">${esc(i.trade)}</td>
        <td>${esc(i.lineType || '')}</td>
        <td><span class="pill">${esc(i.status || '')}</span></td>
        <td>${esc(i.subcontractor || '')}</td>
        <td class="num">${fmtMoney(i.proposalAmount)}</td>
        <td class="num">${fmtMoney(i.contractedValue)}</td>
        <td class="num">${fmtMoney((i.changeOrders || 0) + (i.pendingCor || 0))}</td>
        <td class="num strong">${fmtMoney(i.totalValueBudget)}</td>
        <td class="num">${fmtMoney(i.cashFlowInvested)}</td>
        <td>${esc(fmtDate(i.targetContractDate ?? i.forecastContractDate, locale))}</td>
        <td>${esc(fmtDate(i.dateSubOnSite, locale))}</td>
      </tr>`;
    }).join('');

    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Helvetica Neue',Arial,sans-serif; color:#111; font-size:7pt; }
  .header { display:flex; justify-content:space-between; align-items:flex-start; border-bottom:3px solid #0F1B33; padding-bottom:10px; margin-bottom:10px; }
  .header-left { display:flex; align-items:center; gap:12px; }
  .company-name { font-size:8.5pt; font-weight:700; color:#0F1B33; margin-top:5px; }
  .header-right { text-align:right; }
  .doc-title { font-size:14pt; font-weight:800; color:#0F1B33; letter-spacing:1px; }
  .doc-sub { font-size:8pt; color:#666; margin-top:2px; }
  .summary { display:flex; gap:10px; margin-bottom:10px; }
  .card { flex:1; background:#F7F6F2; border:1px solid #E5E2DB; border-radius:6px; padding:6px 10px; }
  .card .lbl { font-size:6.5pt; text-transform:uppercase; color:#666; letter-spacing:0.4px; }
  .card .val { font-size:10pt; font-weight:700; color:#0F1B33; font-variant-numeric:tabular-nums; }
  table { width:100%; border-collapse:collapse; }
  th { background:#0F1B33; color:#fff; font-size:6.5pt; text-transform:uppercase; letter-spacing:0.3px; padding:4px 5px; text-align:left; }
  th.num, td.num { text-align:right; font-variant-numeric:tabular-nums; }
  td { padding:3.5px 5px; border-bottom:1px solid #EBEBEB; vertical-align:top; }
  tr.div td { background:#FEF3C7; font-weight:700; color:#0F1B33; font-size:7.5pt; }
  td.strong { font-weight:700; }
  .pill { display:inline-block; font-size:6.5pt; padding:1px 5px; border-radius:8px; background:#EEF2F7; color:#0F1B33; }
  .footer { margin-top:12px; padding-top:6px; border-top:1px solid #E5E7EB; font-size:6.5pt; color:#9CA3AF; display:flex; justify-content:space-between; }
</style></head><body>
  <div class="header">
    <div class="header-left">
      ${brand.logoHtml}
      <div class="company-name">${esc(brand.nameUpper)}</div>
    </div>
    <div class="header-right">
      <div class="doc-title">${esc(L.title)}</div>
      <div class="doc-sub"><b>${esc(project.projectNumber ?? '')}</b> — ${esc(project.projectName ?? '')}${project.client ? ` · ${esc(project.client)}` : ''}</div>
    </div>
  </div>

  <div class="summary">
    <div class="card"><div class="lbl">${esc(L.contractBudget)}</div><div class="val">${fmtMoneyFull(totals.total)}</div></div>
    <div class="card"><div class="lbl">${esc(L.contracted)}</div><div class="val">${fmtMoneyFull(totals.contracted)}</div></div>
    <div class="card"><div class="lbl">${esc(L.cors)}</div><div class="val">${fmtMoneyFull(totals.cors)}</div></div>
    <div class="card"><div class="lbl">${esc(L.invested)}</div><div class="val">${fmtMoneyFull(totals.invested)}</div></div>
    <div class="card"><div class="lbl">${esc(L.remaining)}</div><div class="val">${fmtMoneyFull(totals.total - totals.invested)}</div></div>
  </div>

  <table>
    <thead><tr>
      <th>${esc(L.trade)}</th>
      <th style="width:52px;">${esc(L.type)}</th>
      <th style="width:74px;">${esc(L.status)}</th>
      <th style="width:110px;">${esc(L.subcontractor)}</th>
      <th class="num" style="width:66px;">${esc(L.proposal)}</th>
      <th class="num" style="width:66px;">${esc(L.contracted)}</th>
      <th class="num" style="width:56px;">${esc(L.cors)}</th>
      <th class="num" style="width:70px;">${esc(L.total)}</th>
      <th class="num" style="width:62px;">${esc(L.invested)}</th>
      <th style="width:60px;">${esc(L.targetContract)}</th>
      <th style="width:60px;">${esc(L.subOnSite)}</th>
    </tr></thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="footer">
    <span>${esc(brand.nameUpper)}</span>
    <span>${esc(L.generated)} · ${esc(fmtDate(new Date(), locale))}</span>
  </div>
</body></html>`;

    const pdf = await htmlToPdf(html, { format: 'Tabloid', landscape: true, margin: { top: '8mm', right: '8mm', bottom: '8mm', left: '8mm' } });

    const fname = `Buyout_${project.projectNumber ?? 'project'}.pdf`.replace(/[^a-zA-Z0-9_.-]/g, '_');
    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${fname}"`,
      },
    });
  } catch (error: any) {
    console.error('GET /api/buyout/pdf error:', error);
    return NextResponse.json({ error: 'Failed to generate buyout PDF' }, { status: 500 });
  }
}
