export const dynamic = 'force-dynamic';
export const maxDuration = 60;

import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth-options';
import { prisma } from '@/lib/prisma';
import { htmlToPdf } from '@/lib/pdf';
import { appBaseUrl } from '@/lib/app-url';
import { getPdfBrand } from '@/lib/company-brand';
import { getSessionLocale } from '@/lib/i18n/server';

function esc(str: string): string {
  return (str ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const fmtMoney = (v: number | null | undefined): string =>
  '$' + (v ?? 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const fmtDate = (d: Date | string | null | undefined, locale: string): string => {
  if (!d) return '—';
  const dt = typeof d === 'string' ? new Date(d) : d;
  if (isNaN(dt.getTime())) return '—';
  return dt.toLocaleDateString(locale === 'es' ? 'es-ES' : 'en-US', { year: 'numeric', month: 'short', day: 'numeric' });
};

const LABELS = {
  en: {
    title: 'PROJECT BUDGET', version: 'Version', date: 'Budget Date', status: 'Status',
    construction: 'Construction', furnishings: 'Furnishings', subTotal: 'Sub Total',
    op: 'O&P', gl: 'GL', contingency: 'Contingency', grandTotal: 'GRAND TOTAL',
    div: 'Div', item: 'Item', description: 'Description', subVendor: 'Sub / Vendor',
    scheduled: 'Scheduled', changes: 'Changes', revised: 'Revised', pct: '%',
    exclusions: 'Exclusions', assumptions: 'Assumptions', notes: 'Notes',
    acsf: 'Total ACSF', rate: 'Rate/SF',
    generated: 'Generated by koduPM',
  },
  es: {
    title: 'PRESUPUESTO DEL PROYECTO', version: 'Versión', date: 'Fecha', status: 'Estado',
    construction: 'Construcción', furnishings: 'Mobiliario', subTotal: 'Sub Total',
    op: 'O&P', gl: 'GL', contingency: 'Contingencia', grandTotal: 'TOTAL GENERAL',
    div: 'Div', item: 'Ítem', description: 'Descripción', subVendor: 'Sub / Proveedor',
    scheduled: 'Programado', changes: 'Cambios', revised: 'Revisado', pct: '%',
    exclusions: 'Exclusiones', assumptions: 'Supuestos', notes: 'Notas',
    acsf: 'ACSF Total', rate: 'Tarifa/SF',
    generated: 'Generado por koduPM',
  },
} as const;

export async function GET(request: Request, { params }: { params: { id: string } }) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const companyId = (session.user as any)?.companyId ?? '';

    const budget = await prisma.budget.findFirst({
      where: { id: params?.id ?? '', project: { companyId } },
      include: {
        project: true,
        lineItems: { orderBy: { sortOrder: 'asc' } },
      },
    });
    if (!budget) {
      return NextResponse.json({ error: 'Not found' }, { status: 404 });
    }

    const locale = await getSessionLocale();
    const L = LABELS[locale === 'es' ? 'es' : 'en'];
    const brand = await getPdfBrand(companyId, appBaseUrl(), 34);
    const project = budget.project as any;

    const rows = budget.lineItems.map((li: any) => {
      const isSection = li.isSection || li.isSubtotal;
      const cls = isSection ? 'section' : li.isFee ? 'fee' : li.isBelowLine ? 'below' : '';
      return `<tr class="${cls}">
        <td>${esc(li.divisionCode || '')}</td>
        <td>${esc(li.itemNumber || '')}</td>
        <td class="desc">${esc(li.description || '')}</td>
        <td>${esc(li.subVendor || '')}</td>
        <td class="num">${li.scheduledValue ? fmtMoney(li.scheduledValue) : ''}</td>
        <td class="num">${li.currentChanges ? fmtMoney(li.currentChanges) : ''}</td>
        <td class="num">${li.revisedValue ? fmtMoney(li.revisedValue) : ''}</td>
        <td class="num">${li.percentTotal ? li.percentTotal.toFixed(1) + '%' : ''}</td>
      </tr>`;
    }).join('');

    const summaryRow = (label: string, value: string, strong = false) =>
      `<div class="sum-row${strong ? ' strong' : ''}"><span>${esc(label)}</span><span>${esc(value)}</span></div>`;

    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Helvetica Neue',Arial,sans-serif; color:#111; font-size:8pt; }
  .page { padding:0.2in 0; }
  .header { display:flex; justify-content:space-between; align-items:flex-start; border-bottom:3px solid #0F1B33; padding-bottom:12px; margin-bottom:14px; }
  .header-left { display:flex; align-items:center; gap:14px; }
  .company-name { font-size:9pt; font-weight:700; color:#0F1B33; margin-top:6px; }
  .company-addr { font-size:7pt; color:#666; margin-top:2px; }
  .header-right { text-align:right; }
  .doc-title { font-size:16pt; font-weight:800; color:#0F1B33; letter-spacing:1px; }
  .doc-sub { font-size:9pt; color:#666; margin-top:3px; }
  .meta { display:flex; gap:18px; flex-wrap:wrap; background:#F7F6F2; border:1px solid #E5E2DB; border-radius:6px; padding:8px 12px; margin-bottom:12px; font-size:8pt; }
  .meta b { color:#0F1B33; }
  .summary { width:280px; margin-left:auto; margin-bottom:14px; border:1px solid #E5E2DB; border-radius:6px; overflow:hidden; }
  .sum-row { display:flex; justify-content:space-between; padding:4px 12px; border-bottom:1px solid #EEE; }
  .sum-row.strong { background:#0F1B33; color:#C9A96E; font-weight:700; border-bottom:none; }
  table { width:100%; border-collapse:collapse; }
  th { background:#0F1B33; color:#fff; font-size:7pt; text-transform:uppercase; letter-spacing:0.4px; padding:5px 6px; text-align:left; }
  th.num, td.num { text-align:right; font-variant-numeric:tabular-nums; }
  td { padding:4px 6px; border-bottom:1px solid #EBEBEB; vertical-align:top; }
  tr.section td { background:#F7F6F2; font-weight:700; color:#0F1B33; }
  tr.fee td { color:#555; font-style:italic; }
  tr.below td { color:#777; }
  .block { margin-top:14px; }
  .block h3 { font-size:8.5pt; color:#0F1B33; text-transform:uppercase; letter-spacing:0.5px; border-bottom:1px solid #C9A96E; padding-bottom:3px; margin-bottom:5px; }
  .block p { white-space:pre-wrap; font-size:8pt; color:#333; line-height:1.45; }
  .footer { margin-top:16px; padding-top:8px; border-top:1px solid #E5E7EB; font-size:7pt; color:#9CA3AF; display:flex; justify-content:space-between; }
</style></head><body>
<div class="page">
  <div class="header">
    <div class="header-left">
      ${brand.logoHtml}
      <div>
        <div class="company-name">${esc(brand.nameUpper)}</div>
        <div class="company-addr">${brand.addressHtml ?? ''}</div>
      </div>
    </div>
    <div class="header-right">
      <div class="doc-title">${esc(L.title)}</div>
      <div class="doc-sub">${esc(L.version)} ${esc(budget.version)} · ${esc(fmtDate(budget.budgetDate, locale))}</div>
    </div>
  </div>

  <div class="meta">
    <span><b>${esc(project?.projectNumber ?? '')}</b> — ${esc(project?.projectName ?? '')}</span>
    ${project?.client ? `<span>${esc(project.client)}</span>` : ''}
    ${project?.location ? `<span>${esc(project.location)}</span>` : ''}
    ${budget.totalACSF ? `<span><b>${esc(L.acsf)}:</b> ${budget.totalACSF.toLocaleString()} SF</span>` : ''}
    ${budget.sfRate ? `<span><b>${esc(L.rate)}:</b> $${budget.sfRate.toFixed(2)}</span>` : ''}
    <span><b>${esc(L.status)}:</b> ${esc(budget.status)}</span>
  </div>

  <div class="summary">
    ${summaryRow(L.construction, fmtMoney(budget.constructionSubtotal))}
    ${summaryRow(L.furnishings, fmtMoney(budget.furnishingsSubtotal))}
    ${summaryRow(L.subTotal, fmtMoney(budget.subTotalAll))}
    ${summaryRow(`${L.op} (${(budget.opPercent * 100).toFixed(1)}%)`, fmtMoney(budget.opAmount))}
    ${summaryRow(`${L.gl} (${(budget.glPercent * 100).toFixed(1)}%)`, fmtMoney(budget.glAmount))}
    ${summaryRow(`${L.contingency} (${(budget.contingencyPercent * 100).toFixed(1)}%)`, fmtMoney(budget.contingencyAmount))}
    ${summaryRow(L.grandTotal, fmtMoney(budget.grandTotal), true)}
  </div>

  <table>
    <thead><tr>
      <th style="width:36px;">${esc(L.div)}</th>
      <th style="width:52px;">${esc(L.item)}</th>
      <th>${esc(L.description)}</th>
      <th style="width:110px;">${esc(L.subVendor)}</th>
      <th class="num" style="width:78px;">${esc(L.scheduled)}</th>
      <th class="num" style="width:72px;">${esc(L.changes)}</th>
      <th class="num" style="width:78px;">${esc(L.revised)}</th>
      <th class="num" style="width:40px;">${esc(L.pct)}</th>
    </tr></thead>
    <tbody>${rows}</tbody>
  </table>

  ${budget.exclusions ? `<div class="block"><h3>${esc(L.exclusions)}</h3><p>${esc(budget.exclusions)}</p></div>` : ''}
  ${budget.assumptions ? `<div class="block"><h3>${esc(L.assumptions)}</h3><p>${esc(budget.assumptions)}</p></div>` : ''}
  ${budget.notes ? `<div class="block"><h3>${esc(L.notes)}</h3><p>${esc(budget.notes)}</p></div>` : ''}

  <div class="footer">
    <span>${esc(brand.nameUpper)}</span>
    <span>${esc(L.generated)} · ${esc(fmtDate(new Date(), locale))}</span>
  </div>
</div>
</body></html>`;

    const pdf = await htmlToPdf(html, { format: 'Letter', landscape: true, margin: { top: '0.45in', right: '0.45in', bottom: '0.45in', left: '0.45in' } });

    const fname = `Budget_${project?.projectNumber ?? ''}_v${budget.version}.pdf`.replace(/[^a-zA-Z0-9_.-]/g, '_');
    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${fname}"`,
      },
    });
  } catch (error: any) {
    console.error('GET /api/budgets/[id]/pdf error:', error);
    return NextResponse.json({ error: 'Failed to generate budget PDF' }, { status: 500 });
  }
}
