/**
 * lib/cost-codes.ts — Lista de cost codes por proyecto.
 *
 * Fuente: "24-169 Arena Madness — Project Specific Cost Code List" (PDF del PM).
 * Se usa en el módulo Sub Invoices para asignar el cost code a cada invoice
 * de sub sin teclearlo (menú desplegable con código + descripción).
 *
 * NOTA: hoy la lista es común (la de Arena Madness es el estándar CSI del GC).
 * Cuando otro proyecto tenga su propia lista, se puede extender por proyecto.
 */

export type CostCode = { code: string; label: string };

export const COST_CODES: CostCode[] = [
  { code: '01 02 01 07', label: 'PH I - First Aid Kits' },
  { code: '01 02 01 08', label: 'PH I - Porta Johns (temporary construction toilets)' },
  { code: '01 02 01 21', label: 'Job Boxes' },
  { code: '01 02 01 24', label: 'PH I - OSHA posters and job board' },
  { code: '01 02 01 34', label: 'PH I - Site Fence MTCE' },
  { code: '01 02 01 37', label: 'PH I - Procore Software' },
  { code: '01 02 01 42', label: 'PH I - Dumpsters/ Trash removal' },
  { code: '01 31 02', label: 'Project Manager' },
  { code: '01 31 04', label: 'Project Engineer' },
  { code: '01 31 05', label: 'Procurement Support' },
  { code: '01 31 06', label: 'Superintendent' },
  { code: '01 31 09', label: 'Accountant' },
  { code: '01 31 12', label: 'Scheduler' },
  { code: '01 61 13', label: 'Software Licensing Requirements' },
  { code: '01 75 00', label: 'Legal Fees' },
  { code: '01 90 04', label: 'Wifi Hot Spot' },
  { code: '01 90 08', label: 'Drawings' },
  { code: '01 90 10', label: 'Computers/Monitors/iPads' },
  { code: '01 90 11', label: 'Office Supplies' },
  { code: '02 01 05', label: 'Temporary Power and Lighting' },
  { code: '02 01 06', label: 'Provisional Office' },
  { code: '02 01 07', label: 'First Aid Kits' },
  { code: '02 01 08', label: 'Porta Johns (balance of project)' },
  { code: '02 01 17', label: 'Surveyor To Locate all Drain and Coirst crubing Location Flag' },
  { code: '02 01 18', label: 'Drinking Water' },
  { code: '02 01 20', label: 'Equipment; hand tools' },
  { code: '02 01 23', label: 'Construction locks, temporary barricades, temporary storage' },
  { code: '02 01 24', label: 'Safety; PPE' },
  { code: '02 01 41', label: 'Material Handling/ Progress clean labor' },
  { code: '02 01 42', label: 'Dumpsters/ Trash removal' },
  { code: '02 01 43', label: 'Final Cleaning' },
  { code: '02 41 00', label: 'Demolition' },
  { code: '02 82 00', label: 'Asbestos Removal' },
  { code: '03 05 00', label: 'Concrete & Masonry base proposal' },
  { code: '05 12 00', label: 'Structural Metals' },
  { code: '05 70 00', label: 'Ornamental Metals' },
  { code: '06 20 00', label: 'Finish Carpentry base proposal' },
  { code: '07 10 00', label: 'Waterproofing' },
  { code: '07 21 00', label: 'Insulation' },
  { code: '07 50 00', label: 'Roofing' },
  { code: '07 80 00', label: 'Firecaulking' },
  { code: '08 10 00', label: 'Doors and Frames' },
  { code: '08 31 00', label: 'Access Panels' },
  { code: '08 40 00', label: 'Entrances, Storefronts, and Curtain Walls' },
  { code: '08 50 00', label: 'Windows' },
  { code: '08 70 00', label: 'Hardware' },
  { code: '08 80 00', label: 'Glazing Other & Mirrors' },
  { code: '09 20 00', label: 'Drywall and Framing' },
  { code: '09 30 00', label: 'Tile - Floor, Base and Walls Restrooms' },
  { code: '09 53 00', label: 'ACT Acoustical Ceiling Tile' },
  { code: '09 60 00', label: 'minor patch and level to floor substrate at indoor soccer' },
  { code: '09 61 19', label: 'Polished Concrete - Party rooms, Main Gallery, laundry, HVAC, lobby, sales, sports shop, bar/lounge' },
  { code: '09 62 19', label: 'LVT flooring to Level 2' },
  { code: '09 67 00', label: 'Epoxy Flooring Kitchen' },
  { code: '09 91 00', label: 'Painting' },
  { code: '09 94 00', label: 'FRP at Kitchen Low walls' },
  { code: '10 14 00', label: 'Signage' },
  { code: '10 22 00', label: 'Toilet Accessories' },
  { code: '10 23 00', label: 'Toilet Partitions' },
  { code: '10 40 00', label: 'Fire Extinguishers' },
  { code: '10 80 00', label: 'Exterior Awning Canvas' },
  { code: '11 30 00', label: 'Appliances' },
  { code: '11 40 00', label: 'Food Service Equipment' },
  { code: '11 66 00', label: 'Paddle Court Exterior Steel Structure (Clear Span)' },
  { code: '14 40 00', label: 'Vertical Platform Lift' },
  { code: '21 05 00', label: 'Fire Sprinklers' },
  { code: '22 05 00', label: 'Plumbing Base Proposal' },
  { code: '22 40 00', label: 'Plumbing Fixture Package' },
  { code: '23 05 00', label: 'Mechanical base proposal' },
  { code: '26 05 00', label: 'Electrical Base Proposal' },
  { code: '26 50 00', label: 'Lighting' },
  { code: '27 20 00', label: 'Telecommunication infrastructure, Data PreWire' },
  { code: '27 40 00', label: "AV equipment (TV's by owner)" },
  { code: '28 20 00', label: 'Survellience' },
  { code: '28 31 00', label: 'Fire Alarm' },
  { code: '31 30 00', label: 'Base material Gravel Pearock 89 and rock 57 Labor And Materials as per Plan to Proper elevetions.' },
  { code: '32 16 00', label: 'Concrete; curbs for 6x18 for 1139LF at soccer field' },
  { code: '32 17 00', label: 'Repair of Parking Lot Removed and Final Dispose Area approx 7640sf (at soccer court area)' },
  { code: '32 31 00', label: "Fence 8' hight black vinyl Chainlink" },
  { code: '32 39 13', label: 'bollards at trash area' },
  { code: '32 90 00', label: 'Landscape planting and irrigation' },
  { code: '33 40 00', label: 'Construct 10 drainage box 12" x 60" drain 2 12x12 catch basin manhole Install line 362 LF' },
  { code: '50 20 00', label: 'Master Permit Fees' },
  { code: '99 99 01', label: 'Overhead & Profit' },
  { code: '99 99 02', label: 'Liability Insurance' },
];

export function findCostCode(code: string): CostCode | undefined {
  return COST_CODES.find((c) => c.code === code);
}
