import { prisma } from '@/lib/prisma';
import { htmlToPdf } from '@/lib/pdf';
import { appBaseUrl } from '@/lib/app-url';
import { getPdfBrand } from '@/lib/company-brand';
import { downloadFileBuffer } from '@/lib/s3';
import { PDFDocument } from 'pdf-lib';

function esc(str: string): string {
  return (str ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const fmtDate = (d: Date | string | null | undefined, locale: string): string => {
  if (!d) return '—';
  const dt = typeof d === 'string' ? new Date(d) : d;
  if (isNaN(dt.getTime())) return '—';
  return dt.toLocaleDateString(locale === 'es' ? 'es-ES' : 'en-US', { year: 'numeric', month: 'short', day: 'numeric' });
};

const LABELS = {
  en: {
    title: 'SUBMITTAL', type: 'Type', spec: 'Spec Section', priority: 'Priority', status: 'Status',
    subcontractor: 'Subcontractor', requiredDate: 'Required Date', submittedBy: 'Submitted By',
    submittedDate: 'Submitted Date', assignedTo: 'Assigned To', ballInCourt: 'Ball in Court',
    reviewedBy: 'Reviewed By', reviewedDate: 'Reviewed Date', description: 'Description',
    response: 'Response', responseBy: 'Responded by', notes: 'Notes', attachments: 'Attachments',
    generated: 'Generated by koduPM',
    mergedNote: 'merged into this document',
    notMergedNote: 'not mergeable (download separately)',
  },
  es: {
    title: 'SUBMITTAL', type: 'Tipo', spec: 'Sección de especificación', priority: 'Prioridad', status: 'Estado',
    subcontractor: 'Subcontratista', requiredDate: 'Fecha requerida', submittedBy: 'Enviado por',
    submittedDate: 'Fecha de envío', assignedTo: 'Asignado a', ballInCourt: 'En cancha de',
    reviewedBy: 'Revisado por', reviewedDate: 'Fecha de revisión', description: 'Descripción',
    response: 'Respuesta', responseBy: 'Respondido por', notes: 'Notas', attachments: 'Adjuntos',
    generated: 'Generado por koduPM',
    mergedNote: 'anexado a este documento',
    notMergedNote: 'no anexable (descargar por separado)',
  },
} as const;

const STATUS_COLORS: Record<string, { bg: string; text: string; border: string }> = {
  Draft: { bg: '#F3F4F6', text: '#4B5563', border: '#D1D5DB' },
  Submitted: { bg: '#DBEAFE', text: '#1D4ED8', border: '#93C5FD' },
  'Under Review': { bg: '#FEF3C7', text: '#B45309', border: '#FCD34D' },
  Approved: { bg: '#D1FAE5', text: '#047857', border: '#6EE7B7' },
  'Approved as Noted': { bg: '#D1FAE5', text: '#047857', border: '#6EE7B7' },
  'Revise & Resubmit': { bg: '#FEE2E2', text: '#B91C1C', border: '#FCA5A5' },
  'Revise and Resubmit': { bg: '#FEE2E2', text: '#B91C1C', border: '#FCA5A5' },
  Rejected: { bg: '#FEE2E2', text: '#B91C1C', border: '#FCA5A5' },
  Closed: { bg: '#E5E7EB', text: '#374151', border: '#D1D5DB' },
};

const LETTER_W = 612; // 8.5in @72pt
const LETTER_H = 792; // 11in @72pt
const IMG_MARGIN = 36;

export type SubmittalReportResult = {
  bytes: Uint8Array;
  fileName: string;
  submittalNumber: string;
  title: string;
  status: string;
  projectName: string;
  projectNumber: string;
  mergedAttachments: number;
  skippedAttachments: string[];
};

/**
 * Construye el reporte del submittal igual que los COR:
 * portada con el formato koduPM + los anexos del sub (PDFs e imágenes)
 * mergeados en un solo PDF.
 */
export async function buildSubmittalReportPdf(
  submittalId: string,
  companyId: string,
  locale: string
): Promise<SubmittalReportResult | null> {
  const submittal = await prisma.submittal.findFirst({
    where: { id: submittalId, project: { companyId } },
    include: { project: true, attachments: true },
  });
  if (!submittal) return null;

  const L = LABELS[locale === 'es' ? 'es' : 'en'];
  const brand = await getPdfBrand(companyId, appBaseUrl(), 40);
  const project = submittal.project as any;
  const s = submittal as any;
  const sc = STATUS_COLORS[s.status] ?? STATUS_COLORS.Draft;

  // Clasificar anexos: PDFs e imágenes se mergean; el resto solo se lista
  const atts: any[] = s.attachments ?? [];
  const mergeable = (a: any): 'pdf' | 'image' | 'skip' => {
    const type = (a.fileType ?? '').toLowerCase();
    const name = (a.fileName ?? '').toLowerCase();
    if (type === 'application/pdf' || name.endsWith('.pdf')) return 'pdf';
    if (type.startsWith('image/') || /\.(png|jpe?g)$/.test(name)) return 'image';
    return 'skip';
  };
  const skippedNames: string[] = atts.filter((a) => mergeable(a) === 'skip').map((a) => a.fileName ?? 'file');

  const field = (label: string, value: string | null | undefined) =>
    `<div class="cell"><label>${esc(label)}</label><span>${esc(value && value.trim() ? value : '—')}</span></div>`;

  const attachRows = atts.map((a: any, idx: number) => {
    const kind = mergeable(a);
    const note = kind === 'skip' ? L.notMergedNote : L.mergedNote;
    return `<tr><td>${idx + 1}</td><td>${esc(a.fileName ?? '')}</td><td>${esc(a.fileType ?? '')}</td><td style="color:#666;">${esc(note)}</td></tr>`;
  }).join('');

  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Helvetica Neue',Arial,sans-serif; color:#111; font-size:8.5pt; }
  .page { padding:0.2in 0; }
  .header { display:flex; justify-content:space-between; align-items:flex-start; border-bottom:3px solid #0F1B33; padding-bottom:14px; margin-bottom:14px; }
  .header-left { display:flex; align-items:center; gap:14px; }
  .company { font-size:8pt; color:#666; line-height:1.35; margin-top:4px; }
  .header-right { text-align:right; }
  .doc-title { font-size:15pt; font-weight:800; color:#0F1B33; letter-spacing:1px; }
  .doc-num { font-size:11pt; font-weight:700; color:#C9A96E; margin-top:2px; }
  .status-bar { display:flex; gap:8px; margin-bottom:14px; }
  .badge { font-size:7.5pt; font-weight:600; padding:3px 10px; border-radius:10px; }
  .grid { display:grid; grid-template-columns:1fr 1fr 1fr; border:1px solid #E5E2DB; border-radius:6px; overflow:hidden; margin-bottom:14px; }
  .cell { padding:7px 10px; border-bottom:1px solid #EEE; }
  .cell label { display:block; font-size:6.8pt; text-transform:uppercase; color:#888; letter-spacing:0.4px; margin-bottom:2px; }
  .cell span { font-size:8.5pt; font-weight:500; }
  .block { margin-bottom:14px; }
  .block h3 { font-size:8.5pt; color:#0F1B33; text-transform:uppercase; letter-spacing:0.5px; border-bottom:1px solid #C9A96E; padding-bottom:3px; margin-bottom:6px; }
  .block p { white-space:pre-wrap; font-size:8.5pt; color:#333; line-height:1.5; }
  .bic { background:#FEF3C7; border:1px solid #FCD34D; border-radius:6px; padding:8px 12px; margin-bottom:14px; }
  .bic .lbl { font-size:6.8pt; text-transform:uppercase; color:#B45309; letter-spacing:0.4px; }
  .bic .val { font-weight:700; color:#92400E; }
  table { width:100%; border-collapse:collapse; }
  th { background:#0F1B33; color:#fff; font-size:7pt; text-transform:uppercase; padding:5px 8px; text-align:left; }
  td { padding:4px 8px; border-bottom:1px solid #EBEBEB; }
  .footer { margin-top:16px; padding-top:8px; border-top:1px solid #E5E7EB; font-size:7pt; color:#9CA3AF; display:flex; justify-content:space-between; }
</style></head><body>
<div class="page">
  <div class="header">
    <div class="header-left">
      ${brand.logoHtml}
      <div class="company">
        <b>${esc(brand.nameUpper)}</b><br/>
        ${brand.addressHtml ?? ''}
      </div>
    </div>
    <div class="header-right">
      <div class="doc-title">${esc(L.title)}</div>
      <div class="doc-num">${esc(s.submittalNumber)}</div>
    </div>
  </div>

  <div class="status-bar">
    <span class="badge" style="background:${sc.bg};color:${sc.text};border:1px solid ${sc.border}">${esc(s.status)}</span>
    <span class="badge" style="background:#EEF2F7;color:#0F1B33;border:1px solid #CBD5E1">${esc(s.submittalType ?? '')}</span>
    <span class="badge" style="background:#EEF2F7;color:#0F1B33;border:1px solid #CBD5E1">${esc(L.priority)}: ${esc(s.priority ?? 'Normal')}</span>
  </div>

  <div class="grid">
    ${field('Project', `${project?.projectNumber ?? ''} — ${project?.projectName ?? ''}`)}
    ${field(L.spec, s.specSection)}
    ${field(L.subcontractor, s.subcontractor)}
    ${field(L.requiredDate, fmtDate(s.requiredDate, locale))}
    ${field(L.submittedBy, s.submittedBy)}
    ${field(L.submittedDate, fmtDate(s.submittedDate, locale))}
    ${field(L.assignedTo, s.assignedTo)}
    ${field(L.reviewedBy, s.reviewedBy)}
    ${field(L.reviewedDate, fmtDate(s.reviewedDate, locale))}
  </div>

  ${s.ballInCourt ? `<div class="bic"><div class="lbl">${esc(L.ballInCourt)}</div><div class="val">${esc(s.ballInCourt)}${s.ballInCourtRole ? ` (${esc(s.ballInCourtRole)})` : ''}</div></div>` : ''}

  <div class="block"><h3>${esc(s.title ?? L.description)}</h3>${s.description ? `<p>${esc(s.description)}</p>` : ''}</div>

  ${s.responseText ? `<div class="block"><h3>${esc(L.response)}</h3><p>${esc(s.responseText)}</p><p style="margin-top:4px;color:#666;font-size:7.5pt;">${esc(L.responseBy)}: ${esc(s.responseBy ?? '—')} · ${esc(fmtDate(s.responseDate, locale))}</p></div>` : ''}

  ${s.notes ? `<div class="block"><h3>${esc(L.notes)}</h3><p>${esc(s.notes)}</p></div>` : ''}

  ${attachRows ? `<div class="block"><h3>${esc(L.attachments)}</h3><table><thead><tr><th style="width:30px;">#</th><th>File</th><th style="width:110px;">Type</th><th style="width:130px;"></th></tr></thead><tbody>${attachRows}</tbody></table></div>` : ''}

  <div class="footer">
    <span>${esc(brand.nameUpper)}</span>
    <span>${esc(L.generated)} · ${esc(fmtDate(new Date(), locale))}</span>
  </div>
</div>
</body></html>`;

  const coverPdf = await htmlToPdf(html, { format: 'Letter', margin: { top: '0.55in', right: '0.6in', bottom: '0.55in', left: '0.6in' } });

  // Merge: portada koduPM + anexos del sub (PDFs completos, imágenes como página Letter)
  const merged = await PDFDocument.create();
  const coverDoc = await PDFDocument.load(coverPdf);
  const coverPages = await merged.copyPages(coverDoc, coverDoc.getPageIndices());
  coverPages.forEach((p) => merged.addPage(p));

  let mergedCount = 0;
  for (const a of atts) {
    const kind = mergeable(a);
    if (kind === 'skip') continue;
    try {
      const buf = await downloadFileBuffer(a.cloudStoragePath);
      if (kind === 'pdf') {
        const subDoc = await PDFDocument.load(buf, { ignoreEncryption: true });
        const pages = await merged.copyPages(subDoc, subDoc.getPageIndices());
        pages.forEach((p) => merged.addPage(p));
        mergedCount++;
      } else {
        const isPng = (a.fileType ?? '').toLowerCase().includes('png') || (a.fileName ?? '').toLowerCase().endsWith('.png');
        const img = isPng ? await merged.embedPng(buf) : await merged.embedJpg(buf);
        const maxW = LETTER_W - IMG_MARGIN * 2;
        const maxH = LETTER_H - IMG_MARGIN * 2;
        const scale = Math.min(maxW / img.width, maxH / img.height, 1);
        const w = img.width * scale;
        const h = img.height * scale;
        const page = merged.addPage([LETTER_W, LETTER_H]);
        page.drawImage(img, { x: (LETTER_W - w) / 2, y: (LETTER_H - h) / 2, width: w, height: h });
        mergedCount++;
      }
    } catch (err: any) {
      console.error(`Submittal report: could not merge attachment ${a.fileName}:`, err?.message);
      skippedNames.push(a.fileName ?? 'file');
    }
  }

  const bytes = await merged.save();
  const fileName = `Submittal_${String(s.submittalNumber)}.pdf`.replace(/[^a-zA-Z0-9_.-]/g, '_');

  return {
    bytes,
    fileName,
    submittalNumber: s.submittalNumber,
    title: s.title ?? '',
    status: s.status ?? '',
    projectName: project?.projectName ?? '',
    projectNumber: project?.projectNumber ?? '',
    mergedAttachments: mergedCount,
    skippedAttachments: skippedNames,
  };
}
