export const dynamic = 'force-dynamic';
export const maxDuration = 60;

import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth-options';
import { prisma } from '@/lib/prisma';
import { htmlToPdf } from '@/lib/pdf';
import { appBaseUrl } from '@/lib/app-url';
import { getPdfBrand } from '@/lib/company-brand';
import { getSessionLocale } from '@/lib/i18n/server';

function esc(str: string): string {
  return (str ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const fmtMoney = (v: number | null | undefined): string =>
  '$' + (v ?? 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const fmtDate = (d: Date | string | null | undefined, locale: string): string => {
  if (!d) return '—';
  const dt = typeof d === 'string' ? new Date(d) : d;
  if (isNaN(dt.getTime())) return '—';
  return dt.toLocaleDateString(locale === 'es' ? 'es-ES' : 'en-US', { year: 'numeric', month: 'short', day: 'numeric' });
};

const LABELS = {
  en: {
    title: 'PAID BY OWNER — DIRECT PAYMENTS LOG',
    subtitle: 'Direct payments made by the Owner to subcontractors / suppliers per contract agreement',
    pa: 'Pay App', period: 'Period', detail: 'Detail / Paid To', thisPeriod: 'This Period',
    accumulated: 'Accumulated', status: 'Status', total: 'TOTAL PAID BY OWNER TO DATE',
    noPayments: 'No direct payments by the Owner have been recorded in this project.',
    g702ref: 'Reflected in each G702 as line 7b (this period) and 7c (accumulated).',
    generated: 'Generated by koduPM',
  },
  es: {
    title: 'PAGADO POR EL OWNER — LOG DE PAGOS DIRECTOS',
    subtitle: 'Pagos directos del Owner a subcontratistas / suplidores según acuerdo del contrato',
    pa: 'Pay App', period: 'Período', detail: 'Detalle / Pagado a', thisPeriod: 'Este Período',
    accumulated: 'Acumulado', status: 'Estado', total: 'TOTAL PAGADO POR EL OWNER A LA FECHA',
    noPayments: 'No se han registrado pagos directos del Owner en este proyecto.',
    g702ref: 'Se refleja en cada G702 como línea 7b (este período) y 7c (acumulado).',
    generated: 'Generado por koduPM',
  },
} as const;

export async function GET(request: Request, { params }: { params: { id: string } }) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const companyId = (session.user as any)?.companyId ?? '';

    const project = await prisma.project.findFirst({
      where: { id: params?.id ?? '', companyId },
    });
    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 });
    }

    const payApps = await prisma.payApplication.findMany({
      where: { projectId: project.id },
      orderBy: { applicationNumber: 'asc' },
      select: {
        applicationNumber: true,
        periodFrom: true,
        periodTo: true,
        status: true,
        directPayments: true,
        directPaymentsDeduction: true,
        directPaymentsCurrent: true,
        directPaymentsLabel: true,
      },
    });

    const locale = await getSessionLocale();
    const L = LABELS[locale === 'es' ? 'es' : 'en'];
    const brand = await getPdfBrand(companyId, appBaseUrl(), 36);

    let running = 0;
    const rows: string[] = [];
    for (const pa of payApps) {
      const amount = ((pa as any).directPaymentsCurrent || pa.directPaymentsDeduction || 0) as number;
      const accum = (pa.directPayments || 0) as number;
      if (amount <= 0 && accum <= 0) continue;
      running += amount;
      const accumShown = accum > 0 ? accum + amount : running;
      if (accumShown > running) running = accumShown; // respeta la cifra oficial del contrato
      rows.push(`<tr>
        <td class="num">PA #${pa.applicationNumber}</td>
        <td>${esc(fmtDate(pa.periodFrom, locale))} — ${esc(fmtDate(pa.periodTo, locale))}</td>
        <td class="desc">${esc(pa.directPaymentsLabel || 'Direct payment by the Owner to SubS')}</td>
        <td>${esc(pa.status || '')}</td>
        <td class="num">${amount > 0 ? fmtMoney(amount) : '—'}</td>
        <td class="num strong">${fmtMoney(accumShown)}</td>
      </tr>`);
    }

    const body = rows.length
      ? `<table>
          <thead><tr>
            <th class="num" style="width:62px;">${esc(L.pa)}</th>
            <th style="width:170px;">${esc(L.period)}</th>
            <th>${esc(L.detail)}</th>
            <th style="width:80px;">${esc(L.status)}</th>
            <th class="num" style="width:105px;">${esc(L.thisPeriod)}</th>
            <th class="num" style="width:115px;">${esc(L.accumulated)}</th>
          </tr></thead>
          <tbody>${rows.join('')}
            <tr class="total-row">
              <td colspan="4">${esc(L.total)}</td>
              <td class="num"></td>
              <td class="num">${fmtMoney(running)}</td>
            </tr>
          </tbody>
        </table>
        <p class="note">${esc(L.g702ref)}</p>`
      : `<p class="empty">${esc(L.noPayments)}</p>`;

    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Helvetica Neue',Arial,sans-serif; color:#111; font-size:8.5pt; }
  .header { display:flex; justify-content:space-between; align-items:flex-start; border-bottom:3px solid #0F1B33; padding-bottom:14px; margin-bottom:14px; }
  .header-left { display:flex; align-items:center; gap:14px; }
  .company { font-size:8pt; color:#666; line-height:1.35; margin-top:4px; }
  .header-right { text-align:right; max-width:55%; }
  .doc-title { font-size:14pt; font-weight:800; color:#0F1B33; letter-spacing:0.5px; }
  .doc-sub { font-size:8pt; color:#666; margin-top:3px; }
  .project-bar { background:#F7F6F2; border:1px solid #E5E2DB; border-radius:6px; padding:8px 12px; margin-bottom:14px; font-size:9pt; }
  .project-bar b { color:#0F1B33; }
  table { width:100%; border-collapse:collapse; }
  th { background:#0F1B33; color:#fff; font-size:7pt; text-transform:uppercase; letter-spacing:0.4px; padding:6px 8px; text-align:left; }
  th.num, td.num { text-align:right; font-variant-numeric:tabular-nums; }
  td { padding:5px 8px; border-bottom:1px solid #EBEBEB; vertical-align:top; }
  td.strong { font-weight:700; color:#0F1B33; }
  tr.total-row td { background:#0F1B33; color:#C9A96E; font-weight:700; padding:7px 8px; border-bottom:none; }
  .note { margin-top:8px; font-size:7.5pt; color:#777; font-style:italic; }
  .empty { padding:24px; text-align:center; color:#777; border:1px dashed #D1D5DB; border-radius:6px; }
  .footer { margin-top:16px; padding-top:8px; border-top:1px solid #E5E7EB; font-size:7pt; color:#9CA3AF; display:flex; justify-content:space-between; }
</style></head><body>
  <div class="header">
    <div class="header-left">
      ${brand.logoHtml}
      <div class="company">
        <b>${esc(brand.nameUpper)}</b><br/>
        ${brand.addressHtml ?? ''}
      </div>
    </div>
    <div class="header-right">
      <div class="doc-title">${esc(L.title)}</div>
      <div class="doc-sub">${esc(L.subtitle)}</div>
    </div>
  </div>

  <div class="project-bar">
    <b>${esc(project.projectNumber ?? '')}</b> — ${esc(project.projectName ?? '')}
    ${project.client ? ` &nbsp;·&nbsp; ${esc(project.client)}` : ''}
    ${project.location ? ` &nbsp;·&nbsp; ${esc(project.location)}` : ''}
  </div>

  ${body}

  <div class="footer">
    <span>${esc(brand.nameUpper)}</span>
    <span>${esc(L.generated)} · ${esc(fmtDate(new Date(), locale))}</span>
  </div>
</body></html>`;

    const pdf = await htmlToPdf(html, { format: 'Letter', margin: { top: '0.55in', right: '0.6in', bottom: '0.55in', left: '0.6in' } });

    const fname = `PaidByOwner_Log_${project.projectNumber ?? 'project'}.pdf`.replace(/[^a-zA-Z0-9_.-]/g, '_');
    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${fname}"`,
      },
    });
  } catch (error: any) {
    console.error('GET /api/projects/[id]/paid-by-owner/pdf error:', error);
    return NextResponse.json({ error: 'Failed to generate paid-by-owner log' }, { status: 500 });
  }
}
