export const dynamic = 'force-dynamic';
export const maxDuration = 60;

import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth-options';
import { prisma } from '@/lib/prisma';
import { htmlToPdf } from '@/lib/pdf';
import { appBaseUrl } from '@/lib/app-url';
import { getPdfBrand } from '@/lib/company-brand';
import { getSessionLocale } from '@/lib/i18n/server';

function esc(str: string): string {
  return (str ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const fmtDate = (d: Date | string | null | undefined, locale: string): string => {
  if (!d) return '';
  const dt = typeof d === 'string' ? new Date(d) : d;
  if (isNaN(dt.getTime())) return '';
  return dt.toLocaleDateString(locale === 'es' ? 'es-ES' : 'en-US', { month: 'short', day: 'numeric', year: '2-digit' });
};

const dayDiff = (from: Date, to: Date): number =>
  Math.floor((to.getTime() - from.getTime()) / 86400000);

const LABELS = {
  en: {
    title: 'RFI LOG',
    rfi: 'RFI #', submitted: 'Submitted', subject: 'Subject', spec: 'Spec',
    ballInCourt: 'Ball in Court', due: 'Due', responded: 'Responded', daysOpen: 'Days Open',
    status: 'Status', cost: 'Cost Impact', sched: 'Sched. (days)',
    total: 'Total', open: 'Open', underReview: 'Under Review', answered: 'Answered',
    closed: 'Closed', overdue: 'Overdue', generated: 'Generated by koduPM',
  },
  es: {
    title: 'LOG DE RFI',
    rfi: 'RFI #', submitted: 'Enviado', subject: 'Asunto', spec: 'Spec',
    ballInCourt: 'En cancha de', due: 'Vence', responded: 'Respondido', daysOpen: 'Días abierto',
    status: 'Estado', cost: 'Impacto $', sched: 'Tiempo (días)',
    total: 'Total', open: 'Abiertos', underReview: 'En revisión', answered: 'Respondidos',
    closed: 'Cerrados', overdue: 'Vencidos', generated: 'Generado por koduPM',
  },
} as const;

export async function GET(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const companyId = (session.user as any)?.companyId ?? '';

    const { searchParams } = new URL(request.url);
    const projectId = searchParams.get('projectId');
    if (!projectId) return NextResponse.json({ error: 'projectId is required' }, { status: 400 });

    const project = await prisma.project.findFirst({ where: { id: projectId, companyId } });
    if (!project) return NextResponse.json({ error: 'Project not found' }, { status: 404 });

    const items = await prisma.rFI.findMany({
      where: { projectId },
      orderBy: { sequence: 'asc' },
    });

    const locale = await getSessionLocale();
    const L = LABELS[locale === 'es' ? 'es' : 'en'];
    const brand = await getPdfBrand(companyId, appBaseUrl(), 30);

    const now = new Date();
    const isClosed = (s: string) => ['Answered', 'Closed'].includes(s);
    const isOverdue = (i: any) => i.dateDue && new Date(i.dateDue) < now && !isClosed(i.status);

    const stats = {
      total: items.length,
      open: items.filter((i: any) => i.status === 'Open').length,
      underReview: items.filter((i: any) => i.status === 'Under Review').length,
      answered: items.filter((i: any) => i.status === 'Answered').length,
      closed: items.filter((i: any) => i.status === 'Closed').length,
      overdue: items.filter(isOverdue).length,
    };

    const rows = items.map((i: any) => {
      const days = i.responseDate
        ? dayDiff(new Date(i.dateSubmitted), new Date(i.responseDate))
        : dayDiff(new Date(i.dateSubmitted), now);
      const od = isOverdue(i);
      return `<tr>
        <td class="strong">${esc(i.rfiNumber || '')}</td>
        <td>${esc(fmtDate(i.dateSubmitted, locale))}</td>
        <td class="desc">${esc(i.subject || '')}</td>
        <td>${esc(i.specReference || '')}</td>
        <td>${esc(i.ballInCourt || i.assignedTo || '')}</td>
        <td${od ? ' class="od"' : ''}>${esc(fmtDate(i.dateDue, locale))}</td>
        <td>${esc(fmtDate(i.responseDate, locale))}</td>
        <td class="num">${isClosed(i.status) || days >= 0 ? days : ''}</td>
        <td><span class="pill">${esc(i.status || '')}</span></td>
        <td>${esc(i.costImpact && i.costImpact !== 'TBD' ? i.costImpact : '')}</td>
        <td class="num">${i.scheduleImpactDays ?? ''}</td>
      </tr>`;
    }).join('');

    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Helvetica Neue',Arial,sans-serif; color:#111; font-size:7pt; }
  .header { display:flex; justify-content:space-between; align-items:flex-start; border-bottom:3px solid #0F1B33; padding-bottom:10px; margin-bottom:10px; }
  .header-left { display:flex; align-items:center; gap:12px; }
  .company-name { font-size:8.5pt; font-weight:700; color:#0F1B33; margin-top:5px; }
  .header-right { text-align:right; }
  .doc-title { font-size:14pt; font-weight:800; color:#0F1B33; letter-spacing:1px; }
  .doc-sub { font-size:8pt; color:#666; margin-top:2px; }
  .summary { display:flex; gap:10px; margin-bottom:10px; }
  .card { flex:1; background:#F7F6F2; border:1px solid #E5E2DB; border-radius:6px; padding:6px 10px; }
  .card .lbl { font-size:6.5pt; text-transform:uppercase; color:#666; letter-spacing:0.4px; }
  .card .val { font-size:10pt; font-weight:700; color:#0F1B33; font-variant-numeric:tabular-nums; }
  .card.warn .val { color:#B91C1C; }
  table { width:100%; border-collapse:collapse; }
  th { background:#0F1B33; color:#fff; font-size:6.5pt; text-transform:uppercase; letter-spacing:0.3px; padding:4px 5px; text-align:left; }
  th.num, td.num { text-align:right; font-variant-numeric:tabular-nums; }
  td { padding:3.5px 5px; border-bottom:1px solid #EBEBEB; vertical-align:top; }
  td.strong { font-weight:700; }
  td.od { color:#B91C1C; font-weight:700; }
  .pill { display:inline-block; font-size:6.5pt; padding:1px 5px; border-radius:8px; background:#EEF2F7; color:#0F1B33; }
  .footer { margin-top:12px; padding-top:6px; border-top:1px solid #E5E7EB; font-size:6.5pt; color:#9CA3AF; display:flex; justify-content:space-between; }
</style></head><body>
  <div class="header">
    <div class="header-left">
      ${brand.logoHtml}
      <div class="company-name">${esc(brand.nameUpper)}</div>
    </div>
    <div class="header-right">
      <div class="doc-title">${esc(L.title)}</div>
      <div class="doc-sub"><b>${esc(project.projectNumber ?? '')}</b> — ${esc(project.projectName ?? '')}${project.client ? ` · ${esc(project.client)}` : ''}</div>
    </div>
  </div>

  <div class="summary">
    <div class="card"><div class="lbl">${esc(L.total)}</div><div class="val">${stats.total}</div></div>
    <div class="card"><div class="lbl">${esc(L.open)}</div><div class="val">${stats.open}</div></div>
    <div class="card"><div class="lbl">${esc(L.underReview)}</div><div class="val">${stats.underReview}</div></div>
    <div class="card"><div class="lbl">${esc(L.answered)}</div><div class="val">${stats.answered}</div></div>
    <div class="card"><div class="lbl">${esc(L.closed)}</div><div class="val">${stats.closed}</div></div>
    <div class="card warn"><div class="lbl">${esc(L.overdue)}</div><div class="val">${stats.overdue}</div></div>
  </div>

  <table>
    <thead><tr>
      <th style="width:56px;">${esc(L.rfi)}</th>
      <th style="width:58px;">${esc(L.submitted)}</th>
      <th>${esc(L.subject)}</th>
      <th style="width:52px;">${esc(L.spec)}</th>
      <th style="width:90px;">${esc(L.ballInCourt)}</th>
      <th style="width:58px;">${esc(L.due)}</th>
      <th style="width:58px;">${esc(L.responded)}</th>
      <th class="num" style="width:44px;">${esc(L.daysOpen)}</th>
      <th style="width:70px;">${esc(L.status)}</th>
      <th style="width:50px;">${esc(L.cost)}</th>
      <th class="num" style="width:44px;">${esc(L.sched)}</th>
    </tr></thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="footer">
    <span>${esc(brand.nameUpper)}</span>
    <span>${esc(L.generated)} · ${esc(fmtDate(new Date(), locale))}</span>
  </div>
</body></html>`;

    const pdf = await htmlToPdf(html, { format: 'Letter', landscape: true, margin: { top: '8mm', right: '8mm', bottom: '8mm', left: '8mm' } });

    const fname = `RFI_Log_${project.projectNumber ?? 'project'}.pdf`.replace(/[^a-zA-Z0-9_.-]/g, '_');
    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${fname}"`,
      },
    });
  } catch (error: any) {
    console.error('GET /api/rfis/pdf error:', error);
    return NextResponse.json({ error: 'Failed to generate RFI log PDF' }, { status: 500 });
  }
}
