export const dynamic = 'force-dynamic';
export const maxDuration = 60;

import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth-options';
import { prisma } from '@/lib/prisma';
import { htmlToPdf } from '@/lib/pdf';
import { appBaseUrl } from '@/lib/app-url';
import { getPdfBrand } from '@/lib/company-brand';
import { getSessionLocale } from '@/lib/i18n/server';

function esc(str: string): string {
  return (str ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const fmtDate = (d: Date | string | null | undefined, locale: string): string => {
  if (!d) return '';
  const dt = typeof d === 'string' ? new Date(d) : d;
  if (isNaN(dt.getTime())) return '';
  return dt.toLocaleDateString(locale === 'es' ? 'es-ES' : 'en-US', { month: 'short', day: 'numeric', year: '2-digit' });
};

const fmtMoney = (v: number | null | undefined): string =>
  '$' + (v ?? 0).toLocaleString('en-US', { minimumFractionDigits: 2, maximumFractionDigits: 2 });

const dayDiff = (from: Date, to: Date): number =>
  Math.floor((to.getTime() - from.getTime()) / 86400000);

const LABELS = {
  en: {
    title: 'CHANGE ORDER LOG',
    num: 'COR #', date: 'Date', desc: 'Description', sub: 'Subcontractor',
    amount: 'Amount', status: 'Status', approved: 'Approved', days: 'Days Pending',
    decidedBy: 'Decided By',
    total: 'Total CORs', pendingAmt: 'Pending Amount', approvedAmt: 'Approved Amount',
    rejected: 'Rejected', totalAll: 'TOTAL', generated: 'Generated by koduPM',
    amountLabel: 'Amount', pctOfLog: '% of Log Amount', avgDays: 'Avg Days Pending', oldest: 'Oldest COR',
  },
  es: {
    title: 'LOG DE ÓRDENES DE CAMBIO',
    num: 'COR #', date: 'Fecha', desc: 'Descripción', sub: 'Subcontratista',
    amount: 'Monto', status: 'Estado', approved: 'Aprobado', days: 'Días pendiente',
    decidedBy: 'Decidido por',
    total: 'Total CORs', pendingAmt: 'Monto pendiente', approvedAmt: 'Monto aprobado',
    rejected: 'Rechazados', totalAll: 'TOTAL', generated: 'Generado por koduPM',
    amountLabel: 'Monto', pctOfLog: '% del Log', avgDays: 'Prom. Días Pend.', oldest: 'COR más antiguo',
  },
} as const;

export async function GET(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const companyId = (session.user as any)?.companyId ?? '';

    const { searchParams } = new URL(request.url);
    const projectId = searchParams.get('projectId');
    const statusFilter = searchParams.get('status'); // Approved | Pending | Rejected
    if (!projectId) return NextResponse.json({ error: 'projectId is required' }, { status: 400 });

    const project = await prisma.project.findFirst({ where: { id: projectId, companyId } });
    if (!project) return NextResponse.json({ error: 'Project not found' }, { status: 404 });

    const allItems = await prisma.changeOrder.findMany({
      where: { projectId },
      orderBy: { sequence: 'asc' },
    });

    const locale = await getSessionLocale();
    const L = LABELS[locale === 'es' ? 'es' : 'en'];
    const brand = await getPdfBrand(companyId, appBaseUrl(), 30);

    const now = new Date();
    const APPROVED = ['Approved', 'Executed'];
    const PENDING = ['Draft', 'Pending', 'Submitted'];

    // Totals across ALL items (for % calculation)
    const totalsAll = allItems.reduce((acc: any, i: any) => ({
      all: acc.all + (i.totalAmount || 0),
      approved: acc.approved + (APPROVED.includes(i.status) ? (i.totalAmount || 0) : 0),
      pending: acc.pending + (PENDING.includes(i.status) ? (i.totalAmount || 0) : 0),
    }), { all: 0, approved: 0, pending: 0 });

    // Filter items if status param provided
    const items = statusFilter
      ? allItems.filter((i: any) => {
          if (statusFilter === 'Approved') return APPROVED.includes(i.status);
          if (statusFilter === 'Pending') return PENDING.includes(i.status);
          if (statusFilter === 'Rejected') return i.status === 'Rejected';
          return true;
        })
      : allItems;

    const filteredAmount = items.reduce((s: number, i: any) => s + (i.totalAmount || 0), 0);
    const pctOfLog = totalsAll.all > 0 ? ((filteredAmount / totalsAll.all) * 100).toFixed(1) : '0.0';
    const avgDays = items.length > 0
      ? Math.round(items.reduce((s: number, i: any) => {
          const days = i.approvalDate
            ? dayDiff(new Date(i.date), new Date(i.approvalDate))
            : dayDiff(new Date(i.date), now);
          return s + (days >= 0 ? days : 0);
        }, 0) / items.length)
      : 0;
    const oldestDays = items.length > 0
      ? Math.max(...items.map((i: any) => {
          const days = i.approvalDate
            ? dayDiff(new Date(i.date), new Date(i.approvalDate))
            : dayDiff(new Date(i.date), now);
          return days >= 0 ? days : 0;
        }))
      : 0;

    const rows = items.map((i: any) => {
      const days = i.approvalDate
        ? dayDiff(new Date(i.date), new Date(i.approvalDate))
        : dayDiff(new Date(i.date), now);
      return `<tr>
        <td class="strong">${esc(i.corNumber || '')}</td>
        <td>${esc(fmtDate(i.date, locale))}</td>
        <td class="desc">${esc(i.description || '')}</td>
        <td>${esc(i.subcontractor || '')}</td>
        <td class="num strong">${fmtMoney(i.totalAmount)}</td>
        <td><span class="pill">${esc(i.status || '')}</span></td>
        <td>${esc(fmtDate(i.approvalDate, locale))}</td>
        <td class="num">${days >= 0 ? days : ''}</td>
        <td>${esc(i.decidedBy || '')}</td>
      </tr>`;
    }).join('');

    // Build summary cards based on whether we're filtered or not
    let summaryHtml: string;
    let docTitle: string;
    if (statusFilter) {
      const statusLabel = statusFilter.toUpperCase();
      docTitle = `${esc(L.title)} — ${statusLabel}`;
      summaryHtml = `
  <div class="summary">
    <div class="card"><div class="lbl">${esc(L.total)}</div><div class="val">${items.length}</div></div>
    <div class="card"><div class="lbl">${esc(L.amountLabel)}</div><div class="val">${fmtMoney(filteredAmount)}</div></div>
    <div class="card"><div class="lbl">${esc(L.pctOfLog)}</div><div class="val">${pctOfLog}%</div></div>
    <div class="card"><div class="lbl">${esc(L.avgDays)}</div><div class="val">${avgDays}</div></div>
    <div class="card"><div class="lbl">${esc(L.oldest)}</div><div class="val">${oldestDays}d</div></div>
  </div>`;
    } else {
      docTitle = L.title;
      const rejectedCount = allItems.filter((i: any) => i.status === 'Rejected').length;
      summaryHtml = `
  <div class="summary">
    <div class="card"><div class="lbl">${esc(L.total)}</div><div class="val">${allItems.length}</div></div>
    <div class="card"><div class="lbl">${esc(L.pendingAmt)}</div><div class="val">${fmtMoney(totalsAll.pending)}</div></div>
    <div class="card"><div class="lbl">${esc(L.approvedAmt)}</div><div class="val">${fmtMoney(totalsAll.approved)}</div></div>
    <div class="card"><div class="lbl">${esc(L.rejected)}</div><div class="val">${rejectedCount}</div></div>
    <div class="card"><div class="lbl">${esc(L.totalAll)}</div><div class="val">${fmtMoney(totalsAll.all)}</div></div>
  </div>`;
    }

    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Helvetica Neue',Arial,sans-serif; color:#111; font-size:7pt; }
  .header { display:flex; justify-content:space-between; align-items:flex-start; border-bottom:3px solid #0F1B33; padding-bottom:10px; margin-bottom:10px; }
  .header-left { display:flex; align-items:center; gap:12px; }
  .company-name { font-size:8.5pt; font-weight:700; color:#0F1B33; margin-top:5px; }
  .header-right { text-align:right; }
  .doc-title { font-size:14pt; font-weight:800; color:#0F1B33; letter-spacing:1px; }
  .doc-sub { font-size:8pt; color:#666; margin-top:2px; }
  .summary { display:flex; gap:10px; margin-bottom:10px; }
  .card { flex:1; background:#F7F6F2; border:1px solid #E5E2DB; border-radius:6px; padding:6px 10px; }
  .card .lbl { font-size:6.5pt; text-transform:uppercase; color:#666; letter-spacing:0.4px; }
  .card .val { font-size:10pt; font-weight:700; color:#0F1B33; font-variant-numeric:tabular-nums; }
  table { width:100%; border-collapse:collapse; }
  th { background:#0F1B33; color:#fff; font-size:6.5pt; text-transform:uppercase; letter-spacing:0.3px; padding:4px 5px; text-align:left; }
  th.num, td.num { text-align:right; font-variant-numeric:tabular-nums; }
  td { padding:3.5px 5px; border-bottom:1px solid #EBEBEB; vertical-align:top; }
  td.strong { font-weight:700; }
  tr.total td { background:#F7F6F2; font-weight:800; color:#0F1B33; border-top:2px solid #0F1B33; }
  .pill { display:inline-block; font-size:6.5pt; padding:1px 5px; border-radius:8px; background:#EEF2F7; color:#0F1B33; }
  .footer { margin-top:12px; padding-top:6px; border-top:1px solid #E5E7EB; font-size:6.5pt; color:#9CA3AF; display:flex; justify-content:space-between; }
</style></head><body>
  <div class="header">
    <div class="header-left">
      ${brand.logoHtml}
      <div class="company-name">${esc(brand.nameUpper)}</div>
    </div>
    <div class="header-right">
      <div class="doc-title">${esc(docTitle)}</div>
      <div class="doc-sub"><b>${esc(project.projectNumber ?? '')}</b> — ${esc(project.projectName ?? '')}${project.client ? ` · ${esc(project.client)}` : ''}${statusFilter ? ` · ${esc(statusFilter.toUpperCase())}` : ''}</div>
    </div>
  </div>

  ${summaryHtml}

  <table>
    <thead><tr>
      <th style="width:60px;">${esc(L.num)}</th>
      <th style="width:58px;">${esc(L.date)}</th>
      <th>${esc(L.desc)}</th>
      <th style="width:100px;">${esc(L.sub)}</th>
      <th class="num" style="width:80px;">${esc(L.amount)}</th>
      <th style="width:70px;">${esc(L.status)}</th>
      <th style="width:58px;">${esc(L.approved)}</th>
      <th class="num" style="width:50px;">${esc(L.days)}</th>
      <th style="width:90px;">${esc(L.decidedBy)}</th>
    </tr></thead>
    <tbody>${rows}
      <tr class="total">
        <td colspan="4">${esc(L.totalAll)}</td>
        <td class="num">${fmtMoney(filteredAmount)}</td>
        <td colspan="4"></td>
      </tr>
    </tbody>
  </table>

  <div class="footer">
    <span>${esc(brand.nameUpper)}</span>
    <span>${esc(L.generated)} · ${esc(fmtDate(new Date(), locale))}</span>
  </div>
</body></html>`;

    const pdf = await htmlToPdf(html, { format: 'Letter', landscape: true, margin: { top: '8mm', right: '8mm', bottom: '8mm', left: '8mm' } });

    const statusSuffix = statusFilter ? `_${statusFilter}` : '';
    const fname = `Change_Order_Log_${project.projectNumber ?? 'project'}${statusSuffix}.pdf`.replace(/[^a-zA-Z0-9_.-]/g, '_');
    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${fname}"`,
      },
    });
  } catch (error: any) {
    console.error('GET /api/cors/pdf error:', error);
    return NextResponse.json({ error: 'Failed to generate change order log PDF' }, { status: 500 });
  }
}
