export const dynamic = 'force-dynamic';
export const maxDuration = 60;

import { NextResponse } from 'next/server';
import { getServerSession } from 'next-auth';
import { authOptions } from '@/lib/auth-options';
import { prisma } from '@/lib/prisma';
import { htmlToPdf } from '@/lib/pdf';
import { appBaseUrl } from '@/lib/app-url';
import { getPdfBrand } from '@/lib/company-brand';
import { getSessionLocale } from '@/lib/i18n/server';

function esc(str: string): string {
  return (str ?? '').replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

const fmtDate = (d: Date | string | null | undefined, locale: string): string => {
  if (!d) return '';
  const dt = typeof d === 'string' ? new Date(d) : d;
  if (isNaN(dt.getTime())) return '';
  return dt.toLocaleDateString(locale === 'es' ? 'es-ES' : 'en-US', { month: 'short', day: 'numeric', year: '2-digit' });
};

const dayDiff = (from: Date, to: Date): number =>
  Math.floor((to.getTime() - from.getTime()) / 86400000);

const LABELS = {
  en: {
    title: 'SUBMITTAL LOG',
    num: 'Submittal #', spec: 'Spec', desc: 'Description', type: 'Type', sub: 'Subcontractor',
    submitted: 'Submitted', required: 'Required', reviewed: 'Reviewed', days: 'Days in Review',
    ballInCourt: 'Ball in Court', status: 'Status',
    total: 'Total', draft: 'Draft', inReview: 'In Review', approved: 'Approved',
    resubmit: 'Revise & Resubmit', rejected: 'Rejected', generated: 'Generated by koduPM',
  },
  es: {
    title: 'LOG DE SUBMITTALS',
    num: 'Submittal #', spec: 'Spec', desc: 'Descripción', type: 'Tipo', sub: 'Subcontratista',
    submitted: 'Enviado', required: 'Requerido', reviewed: 'Revisado', days: 'Días en revisión',
    ballInCourt: 'En cancha de', status: 'Estado',
    total: 'Total', draft: 'Borrador', inReview: 'En revisión', approved: 'Aprobados',
    resubmit: 'Reenviar', rejected: 'Rechazados', generated: 'Generado por koduPM',
  },
} as const;

export async function GET(request: Request) {
  try {
    const session = await getServerSession(authOptions);
    if (!session?.user) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }
    const companyId = (session.user as any)?.companyId ?? '';

    const { searchParams } = new URL(request.url);
    const projectId = searchParams.get('projectId');
    if (!projectId) return NextResponse.json({ error: 'projectId is required' }, { status: 400 });

    const project = await prisma.project.findFirst({ where: { id: projectId, companyId } });
    if (!project) return NextResponse.json({ error: 'Project not found' }, { status: 404 });

    const items = await prisma.submittal.findMany({
      where: { projectId },
      orderBy: { sequence: 'asc' },
    });

    const locale = await getSessionLocale();
    const L = LABELS[locale === 'es' ? 'es' : 'en'];
    const brand = await getPdfBrand(companyId, appBaseUrl(), 30);

    const now = new Date();
    const IN_REVIEW = ['Submitted', 'Under Review'];
    const APPROVED = ['Approved'];

    const stats = {
      total: items.length,
      draft: items.filter((i: any) => i.status === 'Draft').length,
      inReview: items.filter((i: any) => IN_REVIEW.includes(i.status)).length,
      approved: items.filter((i: any) => APPROVED.includes(i.status)).length,
      resubmit: items.filter((i: any) => i.status === 'Revise and Resubmit').length,
      rejected: items.filter((i: any) => i.status === 'Rejected').length,
    };

    const rows = items.map((i: any) => {
      const days = i.submittedDate
        ? dayDiff(new Date(i.submittedDate), i.reviewedDate ? new Date(i.reviewedDate) : now)
        : null;
      return `<tr>
        <td class="strong">${esc(i.submittalNumber || '')}</td>
        <td>${esc(i.specSection || '')}</td>
        <td class="desc">${esc(i.title || '')}</td>
        <td>${esc(i.submittalType || '')}</td>
        <td>${esc(i.subcontractor || '')}</td>
        <td>${esc(fmtDate(i.submittedDate, locale))}</td>
        <td>${esc(fmtDate(i.requiredDate, locale))}</td>
        <td>${esc(fmtDate(i.reviewedDate, locale))}</td>
        <td class="num">${days ?? ''}</td>
        <td>${esc(i.ballInCourt || i.assignedTo || '')}</td>
        <td><span class="pill">${esc(i.status || '')}</span></td>
      </tr>`;
    }).join('');

    const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><style>
  * { margin:0; padding:0; box-sizing:border-box; }
  body { font-family:'Helvetica Neue',Arial,sans-serif; color:#111; font-size:7pt; }
  .header { display:flex; justify-content:space-between; align-items:flex-start; border-bottom:3px solid #0F1B33; padding-bottom:10px; margin-bottom:10px; }
  .header-left { display:flex; align-items:center; gap:12px; }
  .company-name { font-size:8.5pt; font-weight:700; color:#0F1B33; margin-top:5px; }
  .header-right { text-align:right; }
  .doc-title { font-size:14pt; font-weight:800; color:#0F1B33; letter-spacing:1px; }
  .doc-sub { font-size:8pt; color:#666; margin-top:2px; }
  .summary { display:flex; gap:10px; margin-bottom:10px; }
  .card { flex:1; background:#F7F6F2; border:1px solid #E5E2DB; border-radius:6px; padding:6px 10px; }
  .card .lbl { font-size:6.5pt; text-transform:uppercase; color:#666; letter-spacing:0.4px; }
  .card .val { font-size:10pt; font-weight:700; color:#0F1B33; font-variant-numeric:tabular-nums; }
  .card.warn .val { color:#B91C1C; }
  table { width:100%; border-collapse:collapse; }
  th { background:#0F1B33; color:#fff; font-size:6.5pt; text-transform:uppercase; letter-spacing:0.3px; padding:4px 5px; text-align:left; }
  th.num, td.num { text-align:right; font-variant-numeric:tabular-nums; }
  td { padding:3.5px 5px; border-bottom:1px solid #EBEBEB; vertical-align:top; }
  td.strong { font-weight:700; }
  .pill { display:inline-block; font-size:6.5pt; padding:1px 5px; border-radius:8px; background:#EEF2F7; color:#0F1B33; }
  .footer { margin-top:12px; padding-top:6px; border-top:1px solid #E5E7EB; font-size:6.5pt; color:#9CA3AF; display:flex; justify-content:space-between; }
</style></head><body>
  <div class="header">
    <div class="header-left">
      ${brand.logoHtml}
      <div class="company-name">${esc(brand.nameUpper)}</div>
    </div>
    <div class="header-right">
      <div class="doc-title">${esc(L.title)}</div>
      <div class="doc-sub"><b>${esc(project.projectNumber ?? '')}</b> — ${esc(project.projectName ?? '')}${project.client ? ` · ${esc(project.client)}` : ''}</div>
    </div>
  </div>

  <div class="summary">
    <div class="card"><div class="lbl">${esc(L.total)}</div><div class="val">${stats.total}</div></div>
    <div class="card"><div class="lbl">${esc(L.draft)}</div><div class="val">${stats.draft}</div></div>
    <div class="card"><div class="lbl">${esc(L.inReview)}</div><div class="val">${stats.inReview}</div></div>
    <div class="card"><div class="lbl">${esc(L.approved)}</div><div class="val">${stats.approved}</div></div>
    <div class="card"><div class="lbl">${esc(L.resubmit)}</div><div class="val">${stats.resubmit}</div></div>
    <div class="card warn"><div class="lbl">${esc(L.rejected)}</div><div class="val">${stats.rejected}</div></div>
  </div>

  <table>
    <thead><tr>
      <th style="width:64px;">${esc(L.num)}</th>
      <th style="width:52px;">${esc(L.spec)}</th>
      <th>${esc(L.desc)}</th>
      <th style="width:70px;">${esc(L.type)}</th>
      <th style="width:90px;">${esc(L.sub)}</th>
      <th style="width:58px;">${esc(L.submitted)}</th>
      <th style="width:58px;">${esc(L.required)}</th>
      <th style="width:58px;">${esc(L.reviewed)}</th>
      <th class="num" style="width:46px;">${esc(L.days)}</th>
      <th style="width:86px;">${esc(L.ballInCourt)}</th>
      <th style="width:76px;">${esc(L.status)}</th>
    </tr></thead>
    <tbody>${rows}</tbody>
  </table>

  <div class="footer">
    <span>${esc(brand.nameUpper)}</span>
    <span>${esc(L.generated)} · ${esc(fmtDate(new Date(), locale))}</span>
  </div>
</body></html>`;

    const pdf = await htmlToPdf(html, { format: 'Letter', landscape: true, margin: { top: '8mm', right: '8mm', bottom: '8mm', left: '8mm' } });

    const fname = `Submittal_Log_${project.projectNumber ?? 'project'}.pdf`.replace(/[^a-zA-Z0-9_.-]/g, '_');
    return new NextResponse(new Uint8Array(pdf), {
      headers: {
        'Content-Type': 'application/pdf',
        'Content-Disposition': `attachment; filename="${fname}"`,
      },
    });
  } catch (error: any) {
    console.error('GET /api/submittals/pdf error:', error);
    return NextResponse.json({ error: 'Failed to generate submittal log PDF' }, { status: 500 });
  }
}
